services:
  bot:
    image: ghcr.io/floatingmilkshake/azusa
    restart: on-failure
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
      - type: bind
        source: ./config.json
        target: /app/config.json
    labels: [ "com.centurylinklabs.watchtower.scope=azusa" ]
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - type: bind
        source: ./redisdata
        target: /data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    command: --appendonly yes
    labels: [ "com.centurylinklabs.watchtower.scope=azusa" ]
  watchtower:
    image: nickfedor/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    command: --interval 30 --label-enable --scope azusa
    restart: always
    labels: [ "com.centurylinklabs.watchtower.scope=azusa" ]
