name: docker-build

on:
  pull_request:
  push:

jobs:
  build:
    uses: FloatingMilkshake/actions/.forgejo/workflows/docker/docker-build-push.yml@main
    with:
      image-name: floatingmilkshake/azusa
      push: ${{ forgejo.event_name == 'push' && forgejo.ref == 'refs/heads/main' }}
    secrets:
      registry-token: ${{ secrets.REGISTRY_TOKEN }}
